### ISSUE TITLE
hakai_salmon_data: merge event with occurrence

### ISSUE THREAD

**Issue by albenson-usgs** [marinebon/ioos_bio_data_scripts#8]
After performing a merge in R between the event file and occurrence file using eventID there are 285 occurrences with no latitude/longitude. Is this accurate?

**Comment by Br-Johnson** [comment]
This was a result of including events that captured no fish, and a result of including fish that were not part of the standard surveys. This is fixed now!

**Comment by 7yl4r** [comment]
Sorry I keep dropping in and causing trouble but : sampling events with
zero fish (absence data) could potentially be *very* valuable for analyzing
sampling effort. Are you sure removing these is best?

I would hate to see absence data getting excluded; I believe we need much
more of it.

**Comment by albenson-usgs** [comment]
Hmm...you make a good point Tylar. However, these occurrences did not have a lat/lon and so would be dropped in OBIS as not meeting the minimum requirements for occurrences. Brett, would it be possible to include the lat/lon for these occurrences?

**Comment by Br-Johnson** [comment]
In this case, when I say we captured no fish it's because we didn't set the net on a particular survey (because of bad weather or something). So their not true absences. 

Tylar brings up a great point though. In the framework of OBIS-ENV Data format (Darwin Occurrence Core with measurementOrFact extension), how and where do we accurately and consistently represent absence data?

**Comment by albenson-usgs** [comment]
There are two ways to do this. One is the required term occurrenceStatus. You set occurrenceStatus = "absent". You can also set indivdualCount = 0 if it makes sense to use that term (for instance it wouldn't make sense to use individualCount if the count of the species is percent cover).
